name: learn-github-actions-pr
on:  
  pull_request:
    branches: 
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dylanvann/check-pull-request-title@v1
      with:
        # Match pull request titles in the form UI-1234 - Message.
        pattern: '^((([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?) - '